server:
  port: "5000"

database:
  host: "db"
#  host: "127.0.0.1"
  port: "3306"
  database: "main"
  username: "root"
  password: "root"
  max_idle_conns: 50
  max_open_conns: 80

jwt:
  secret: "YlD88vos5PiSx1uRdlIu"
  expHour: 24

rateLimit:
  reqPerMin: 10
